package pl.coderslab.entity;

import java.sql.SQLException;
import java.util.Arrays;

public class MainDao {
    public static void main(String[] args) throws SQLException {
        DBUtil.getConnection();
//        create
//        UserDao userDao = new UserDao();
//        User user = new User("Erick", "erick@gmail.com", "erick1");
//        System.out.println(user.getId());
//        userDao.create(user);
//        System.out.println(user.getId());

//        update
//        User user = new User("Tomek", "tomek@gmail.com", "tomek1");
//        user.setId(2);
//        userDao.update(user);
//        System.out.println(user.getId());

//        read
//        UserDao userDao = new UserDao();
//        User userReaded = userDao.read(2);
//        System.out.println(userReaded);

//        findAll
//        UserDao userDao = new UserDao();
//        User[] users = userDao.findAll();
//        System.out.println(Arrays.toString(users));

//        delete
//        UserDao userDao = new UserDao();
//        userDao.delete(6);

    }
}
